name: pr-actions
on: [pull_request]

jobs:
  backend-strelka-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:

          python-version: '3.x'

          architecture: 'x64'
      - name: Install dependencies
        run: |
          apt-get install automake \
            build-essential \
            libfuzzy-dev \
            libarchive-dev \
            libmagic-dev \
            python3-setuptools \
            tesseract-ocr 
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          pip install -r build/python/backend/requirements.txt

      - name: Test with pytest
        run: |
          pytest
      

